### ISSUE TITLE
Sugestão de medida provisória para o Combat Tracker

### ISSUE THREAD

**Issue by paulobmedeiros** [burobrasil/olddragon2e-foundryvtt#25]
A rolagem de iniciativa ainda não está funcionando. Com isso em mente, estou conseguindo contornar o problema inserindo manualmente valores para separar os que jogam antes ou depois dos monstros, mas acho que seria uma mão na roda já ter algo automático, mesmo que provisoriamente. Sei que o sistema base de iniciativa do Old Dragon 2 é diferente do padrão e que isso pode dificultar bastante a implementação em VTTs. Mas, como não entendo nada sobre como programar esse tipo de coisa, vou sugerir uma solução temporária que eu presumo que seja mais fácil de implementar.

Minha ideia seria inserir logo de cara o sistema de iniciativa individual apresentado no LB2 (rolagem de d12). Assim, já haveria um sistema de iniciativa funcional no jogo, mesmo que provisório. Além disso, esse sistema poderia ser aproveitado futuramente como uma regra opcional de iniciativa.

**Comment by jmonteiro** [comment]
De maneira provisória, temos agora rolagem usando a regra de d12 do LB2.
