### ISSUE TITLE
[Sugestão] Alternativa para rolagem de ataque para Monstros

### ISSUE THREAD

**Issue by pedrualves** [burobrasil/olddragon2e-foundryvtt#52]
Enquanto a rolagem de ataque para monstros não é implementada.
Seria possível e viável habilitar comandos inline para rolagens(api default do foundry) na aba de habilidades?
Por exemplo o mesmo padrão que é utilizado nos diários?

![image](https://github.com/burobrasil/olddragon2e-foundryvtt/assets/1184178/16f5b98d-a58c-4979-8b30-db00ac0fa52f)

Obrigado, att.

**Comment by jmonteiro** [comment]
Lançado na versão 0.2.0.

![SCR-20240401-qfpd](https://github.com/burobrasil/olddragon2e-foundryvtt/assets/3586/ead22113-2d08-46c6-976d-c1ab1f62d63a)
